Update to R 3.6.1
keboola/r-transformation pull request #4
Opened 2019-10-03 15:31 UTC by pivnicek

https://github.com/keboola/devops/issues/129

2019-10-03 20:23 UTC, odinuv requested changes
somehow that 1.9.2 tag didn't make it to travis, so it wasn't deployed

![image](https://user-images.githubusercontent.com/4319320/66161268-33971680-e62c-11e9-9b04-9743b601e32c.png)

might be a travis hiccup, create a new tag if the 1.9.2 is broken

2019-10-04 08:15 UTC, pivnicek commented
Weird.  I guess I'll try deleting and re-tagging it

2019-10-04 10:46 UTC, pivnicek commented
@odinuv ping :-)

2019-10-04 10:57 UTC, odinuv approved these changes

2019-10-04 11:00 UTC, merged